/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect_4_deneme;

import java.awt.Button;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author M. Furkan Çankaya
 */
public class oyun extends javax.swing.JFrame {

    /**
     * Creates new form oyun
     */
    int sayac=0;
    int sıra=0;
    public oyun() {
        initComponents();
        button7.setEnabled(false);
        button8.setEnabled(false);
        button9.setEnabled(false);
        button10.setEnabled(false);
        button11.setEnabled(false);
        button12.setEnabled(false);
        button13.setEnabled(false);
        button14.setEnabled(false);
        button15.setEnabled(false);
        button16.setEnabled(false);
        button17.setEnabled(false);
        button18.setEnabled(false);
        //button19.setEnabled(false);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("button2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("button3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setLabel("button4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setLabel("button5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setLabel("button6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setLabel("button7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setLabel("button8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setLabel("button9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button10.setLabel("button10");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button11.setLabel("button11");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        button12.setLabel("button12");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });

        button13.setLabel("button13");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });

        button14.setLabel("button14");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });

        button15.setLabel("button15");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });

        button16.setLabel("button16");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });

        button17.setLabel("button17");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });

        button18.setLabel("button18");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button13, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button14, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button15, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button10, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(button16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button11, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(button17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button12, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(button18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(button14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(button16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(button9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        sıra++;
        if(sıra%2==0){
            button1.setBackground(Color.green);
            buton1();
        
        }
        else{
        button1.setBackground(Color.red);
        buton2();
        }
        button7.setEnabled(true);
        sayac++;
        button1.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_button1ActionPerformed
public void buton1(){
            Button dizi[][]={{button1,button2,button3,button4,button5,button6},
                        {button7,button8,button9,button10,button11,button12},
                        {button13,button14,button15,button16,button17,button18}
            
                        };
            sayac=0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 6; j++) {
                if(j!=5)
                {
                if(dizi[i][j].getBackground().equals(dizi[i][j+1].getBackground()) && dizi[i][j].getBackground().equals(Color.green))
                 {
                    sayac++;
                 }
                else{
                    sayac=0;
                    break;
                    }
                }
                if(sayac==2)
                    break;
            }
            if(sayac==2)
                break;
            sayac=0;
            
        }
        if(sayac>=2){
                    
            
            JOptionPane.showMessageDialog(this, "Kazandınız", "Tebrikler", JOptionPane.INFORMATION_MESSAGE);
            sonuç s = new sonuç();
            s.setVisible(true);
            this.dispose();
                }
        
        else{
            for (int i = 0; i < 6; i++) {
                for (int j = 0; j < 3; j++) {
                    if(j!=2){
                        if(dizi[j][i].getBackground().equals(dizi[j+1][i].getBackground()) && dizi[j][i].getBackground().equals(Color.green))
                 {
                    sayac++;
                 }
                else{
                    sayac=0;
                    break;
                    }
                        
                    }
                    if(sayac==2){
                        break;
                    }
                }
                if(sayac==2){
                    break;
                }
                sayac=0;
            }
            if(sayac>=2){
                JOptionPane.showMessageDialog(this, "Kazandınız", "Tebrikler", JOptionPane.INFORMATION_MESSAGE);
            sonuç s = new sonuç();
            s.setVisible(true);
            this.dispose();
            }
        }
}

public void buton2(){
            Button dizi[][]={{button1,button2,button3,button4,button5,button6},
                        {button7,button8,button9,button10,button11,button12},
                        {button13,button14,button15,button16,button17,button18}
            
                        };
            sayac=0;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 6; j++) {
                if(j!=5)
                {
                if(dizi[i][j].getBackground().equals(dizi[i][j+1].getBackground()) && dizi[i][j].getBackground().equals(Color.red))
                 {
                    sayac++;
                 }
                else{
                    sayac=0;
                    break;
                    }
                }
                if(sayac==2)
                    break;
            }
            if(sayac==2)
                break;
            sayac=0;
            
        }
        if(sayac>=2){
                    
            
            JOptionPane.showMessageDialog(this, "Kazandınız", "Tebrikler", JOptionPane.INFORMATION_MESSAGE);
            sonuç s = new sonuç();
            s.setVisible(true);
            this.dispose();
                }
        
        
        
        
        else{
            for (int i = 0; i < 6; i++) {
                for (int j = 0; j < 3; j++) {
                    if(j!=2){
                        if(dizi[j][i].getBackground().equals(dizi[j+1][i].getBackground()) && dizi[j][i].getBackground().equals(Color.red))
                 {
                    sayac++;
                 }
                else{
                    sayac=0;
                    break;
                    }
                        
                    }
                    if(sayac==2){
                        break;
                    }
                }
                if(sayac==2){
                    break;
                }
                sayac=0;
            }
            if(sayac>=2){
                JOptionPane.showMessageDialog(this, "Kazandınız", "Tebrikler", JOptionPane.INFORMATION_MESSAGE);
            sonuç s = new sonuç();
            s.setVisible(true);
            this.dispose();
            }
        }
        
}

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button7.setBackground(Color.green);
            buton1();
        }
        else{
        button7.setBackground(Color.red);
        buton2();
        }
        button13.setEnabled(true);
        sayac++;
        button7.setEnabled(false);
    }//GEN-LAST:event_button7ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button2.setBackground(Color.green);
            buton1();
        }
        else{
        button2.setBackground(Color.red);
        buton2();
        }
        button8.setEnabled(true);
        sayac++;
        button2.setEnabled(false);
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button8.setBackground(Color.green);
            buton1();
        }
        else{
        button8.setBackground(Color.red);
        buton2();
        }
        button14.setEnabled(true);
        sayac++;
        button8.setEnabled(false);
        
    }//GEN-LAST:event_button8ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button3.setBackground(Color.green);
            buton1();
        }
        else{
        button3.setBackground(Color.red);
        buton2();
        }
        button9.setEnabled(true);
        sayac++;
        button3.setEnabled(false);
        
    }//GEN-LAST:event_button3ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button9.setBackground(Color.green);
            buton1();
        }
        else{
        button9.setBackground(Color.red);
        buton2();
        }
        button15.setEnabled(true);
        sayac++;
        button9.setEnabled(false);
        
    }//GEN-LAST:event_button9ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button13.setBackground(Color.green);
            buton1();
        }
        else{
        button13.setBackground(Color.red);
        buton2();
        }
        sayac++;
        button13.setEnabled(false);
        
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button14.setBackground(Color.green);
            buton1();
        }
        else{
        button14.setBackground(Color.red);
        buton2();
        }
        sayac++;
        button14.setEnabled(false);
        
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button15.setBackground(Color.green);
            buton1();
        }
        else{
        button15.setBackground(Color.red);
        buton2();
        }
        sayac++;
        button15.setEnabled(false);
        
            
    }//GEN-LAST:event_button15ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button4.setBackground(Color.green);
            buton1();
        }
        else{
        button4.setBackground(Color.red);
        buton2();
        }
        button10.setEnabled(true);
        sayac++;
        button4.setEnabled(false);
        
    }//GEN-LAST:event_button4ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button10.setBackground(Color.green);
            buton1();
        }
        else{
        button10.setBackground(Color.red);
        buton2();
        }
        button16.setEnabled(true);
        sayac++;
        button10.setEnabled(false);
        
    }//GEN-LAST:event_button10ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button16.setBackground(Color.green);
            buton1();
        }
        else{
        button16.setBackground(Color.red);
        buton2();
        }
        sayac++;
        button16.setEnabled(false);
        
    }//GEN-LAST:event_button16ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button5.setBackground(Color.green);
            buton1();
        }
        else{
        button5.setBackground(Color.red);
        buton2();
        }
        button11.setEnabled(true);
        sayac++;
        button5.setEnabled(false);
        
    }//GEN-LAST:event_button5ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button11.setBackground(Color.green);
            buton1();
        }
        else{
        button11.setBackground(Color.red);
        buton2();
        }
        button17.setEnabled(true);
        sayac++;
        button11.setEnabled(false);
        
    }//GEN-LAST:event_button11ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button17.setBackground(Color.green);
            buton1();
        }
        else{
        button17.setBackground(Color.red);
        buton2();
        }
//        button19.setEnabled(true);
        sayac++;
        button17.setEnabled(false);
        
    }//GEN-LAST:event_button17ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button6.setBackground(Color.green);
            buton1();
        }
        else{
        button6.setBackground(Color.red);
        buton2();
        }
        button12.setEnabled(true);
        sayac++;
        button6.setEnabled(false);
        
    }//GEN-LAST:event_button6ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button12.setBackground(Color.green);
            buton1();
        }
        else{
        button12.setBackground(Color.red);
        buton2();
        }
        button18.setEnabled(true);
        sayac++;
        button12.setEnabled(false);
        
    }//GEN-LAST:event_button12ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        // TODO add your handling code here:
        sıra++;
        if(sıra%2==0){
            button18.setBackground(Color.green);
            buton1();
        }
        else{
        button18.setBackground(Color.red);
        buton2();
        }
        sayac++;
        button18.setEnabled(false);
        
        
    }//GEN-LAST:event_button18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    // End of variables declaration//GEN-END:variables
}
